server:
  port: 8080
spring:

  mail:
    host: smtp.qq.com
    # 你的QQ邮箱，这里为发件人，填自己的即可
    username: 2298266523@qq.com
    # 你的QQ邮箱授权码
    password: kicioxqetinndjde
  application:
    #应用名称可选
    name: reggie_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 229826
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
reggie:
  path: E:\Reggie\Project\Reggie\DICM\